openapi: 3.0.1
info:
  title: Gallantries / Galaxy / GTN Video Library
  description: A library of GTN Tutorial Recordings by the GTN Community
  license:
    name: AGPL-3.0
    url: https://github.com/gallantries/video-library/blob/main/LICENSE.txt
  version: 1.0.0
servers:
- url: https://gallantries.github.io/video-library/api/
- url: http://localhost:4000/video-library/api/

paths:
  /videos.json:
    get:
      summary: List all videos
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /sessions.json:
    get:
      summary: List all sessions
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /tags.json:
    get:
      summary: Get tags
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /tags/{tagId}.json:
    get:
      parameters:
      - name: tagId
        in: path
        description: ID of the tag
        required: true
        schema:
          type: string
      summary: Get information about a specific tag
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /by-material/topics/{topicId}/tutorials/{tutorialId}/{material}.html.json:
    get:
      parameters:
      - name: topicId
        in: path
        description: ID of the topic
        required: true
        schema:
          type: string
      - name: tutorialId
        in: path
        description: ID of the tutorial
        required: true
        schema:
          type: string
      - name: material
        in: path
        description: slides or tutorial, whichever material type it is.
        required: true
        schema:
          type: string
      summary: Get videos that cover a specific training material (and possibly more)
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /by-material.json:
    get:
      summary: Get the entire video database by-material
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /modules.json:
    get:
      summary: Get the database of available modules
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /modules/{module}.json:
    get:
      summary: Get the details about a specific module (probably not a useful route, all info is in /modules.json)
      parameters:
      - name: module
        in: path
        description: ID of the module
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
